language: node_js # 指定语言环境
node_js:
  - "10" # 指定 NodeJS 版本
dist: trusty # 指定系统版本。trusty 是指 Ubuntu 14.04 发行版的名称
sudo: required # 是否需要 sudo 权限

branches: # 指定要构建的分支
  only: # only 表示只构建以下分支
  - dev

install:
  - source print.sh "install"
  - git branch
  - hexo -v
